


--auricular
INSERT INTO producto VALUES (0,"Auricular On Ear Philips TAH4205BK Negro","Con el auricular Philips contas con 29 horas de tiempo de reproducción, carga rápida, botón de refuerzo de graves, graves enriquecidos, sonido claro, micrófono para llamadas con manos libres, botón multifunción. Controla fácilmente la música y las llamadas, excelente sistema de aislación de sonido, controladores de 32mm,  almohadillas suaves para mayor comodidad, banda sujetadora acolchada, ligera y ajustable, diseño plegable para guardarlo fácilmente.",120,35259,"https://images.freeimages.com/uploads/11086355/4e934d53-8a14-4564-8505-96790a486ced.png",0,0,1,"auriculares");

INSERT INTO producto VALUES (0,"Auricular Moonki MH-613 On Ear Azul","Auricular Moonki On Ear ajustable, drivers 40mm, frecuencia de respuesta 20Hz-20Khz, conector jack 3.5mm, largo del cable 1.5mts, con almohadilla aisladora de sonido, vincha regulable.",125,8321,"https://images.freeimages.com/uploads/11086355/3bc46f69-2ca7-4357-b893-bcc7b14b7d63.png",0,0,1,"auriculares");

INSERT INTO producto VALUES (0,"Auricular On Ear Philips TAH4105WT Con Cable","Auriculares On Ear, graves enriquecidos, sonido claro, diseño plegable para guardarlo fácilmente, micrófono para llamadas con manos libres, control remoto que permite reproducir o detener canciones y atender llamadas con solo pulsar un botón, excelente sistema de aislación de sonido, controladores de 32mm, almohadillas suaves para mayor comodidad, banda sujetadora acolchada, ligera y ajustable.",225,17689,"https://images.freeimages.com/uploads/11086355/52adb9b5-47b7-4107-8ef9-2bf08780e8ed.png",0,0,1,"auriculares");
--Compus
INSERT INTO producto VALUES (0,"Computadora Gfast H-350 Intel Core I3 Slim","Pc de escritorio Gfast slim cuenta con un procesador Intel Core I3, una memoria RAM de 8GB DDR4 y un almacenamiento de 240GBSSD, el sistema operativo es Windows 11 y una potencia de 300 watts",30,305779,"https://images.freeimages.com/uploads/11086355/a73776ed-a624-4396-8d40-6f210f3ad1e5.png",0,0,1,”computadoras”);

INSERT INTO producto VALUES (0,"Computadora Gfast X300 Captain Intel Core I3","Desktop Gamer Gfast cuenta con un procesador Intel Core I3 10100F, memoria RAM de 16GB DDR4 RGB, con un almacenamiento de 480GB SSD, placa de video Nvidia GTX 1660, sistema operativo Windows 11, gabinete Gamer vidrio mas 6 colores RGB, potencia de 800 watts.",50 ,615843,"https://images.freeimages.com/uploads/11086355/e561c347-ca21-4b14-b1b7-ae975c101fac.png",0,0,1,”computadoras”);

INSERT INTO producto VALUES (0,"Computadora Gfast Child Intel Celeron N4020","Computadora Gfast esta equipada con un Procesador INTEL CELERON, 4 GB de RAM DDR4, Disco SSD de 120GB, todo en un gabinete CI-S607B y con Sistema Operativo Windows 11 Home, incluye teclado, mouse.",100,195627,"https://images.freeimages.com/uploads/11086355/b11beb31-70ed-4ab5-8646-d30b14790855.png",0,0,1,"computadoras",0,0,1,”computadoras”);

--aires

INSERT INTO producto VALUES (0,"Aire Acondicionado Split Samsung AR18BSH 5000Watts f/c Inverter"," El aire acondicionado Samsung ofrece un confort inmediato con un gran ahorro de energía, gracias a su tecnología Inverter, mantiene la temperatura deseada sin apagarse y encenderse con frecuencia, generando menos fluctuación,  además, cuenta con filtro reutilizable que captura el polvo contaminantes y alérgenos en el aire, con su función Fast podrás enfriar tu ambiente de forma eficaz en el menor tiempo posible, siendo ideal para un alivio inmediato del calor exterior, además, el modo Sleep controla y ajusta automáticamente la temperatura para crear las condiciones ideales en cada etapa del ciclo de sueño, utilizando menos energía que el enfriamiento normal.",125,738050,"https://images.freeimages.com/uploads/11086355/b5072749-2e0f-4a7a-9610-d46110f69a47.png",0,0,1,"aires");

INSERT INTO producto VALUES (0,"Aire Acondicionado Split Hitachi HSP3200FCECO 3200 Watts f/c","El Aire Acondicionado Hitachi HSP3200FCECO, split frío/calor posee 2752 frigorías y 3200 watts de potencia, con la función Sleep, ajusta de forma automática la temperatura del hambiente logrando mayor confort en el descanso, control de caudal de aire, función Turbo, al activar esta función en modo frío se activará el máximo enfriamient a 16øC, en modo calor se activará la máxima calefacción a 31øC, función Deshumidificación, reduce la humedad del aire, función Smart, el modo de funcionamiento y la temperatura seleccionada se establece automáticamente en base a la temperatura del ambiente.",105,379999,"https://images.freeimages.com/uploads/11086355/46f59441-7895-46a0-9662-e4bbdf5e3bd8.png",0,0,1,"aires");

INSERT INTO producto VALUES (0,"Aire Acondicionado Split Siam SMS50HA4CN 5200 Watts f/c","Aire Acondicionado Siam, con una  gran potencia de 5200 watts y una potencia en frigorías 4.472, lo que garantiza un alto rendimiento en la climatización de espacios amplios, además, cuenta con una eficiencia energética A que reduce el consumo de electricidad y contribuye al cuidado del medio ambiente, este equipo también se destaca por ser súper silencioso, lo que permite disfrutar de un ambiente fresco y cómodo sin ruidos molestos, el control remoto multifunción y los filtros lavables hacen que el mantenimiento y la operación sean fáciles y prácticos, es una excelente opción para quienes buscan un equipo eficiente, potente y silencioso para mantener sus espacios frescos durante todo el año.",300,533499,"https://images.freeimages.com/uploads/11086355/72997100-4263-48c1-9fa0-3e979c169e23.png",0,0,1,"aires");
